Increasing http client timeout.
kronostechnologies/simple-http-client pull request #1
Opened 2020-12-01 16:18 UTC by mdastous

2020-12-01 17:29 UTC, nvanheuverzwijn commented
@mdastous @antoinedeschenes On devrait mettre ça en variable d'environnement.
Genre `os.Getenv("HTTP_TIMEOUT")`, mettre HTTP_TIMEOUT default à 5 secondes dans le dockerfile.

2020-12-01 18:08 UTC, antoinedeschenes commented
je defaulterais dans le code, ça a des chances de pas servir dans docker

2020-12-01 18:49 UTC, nvanheuverzwijn commented
@antoinedeschenes J'trouve ça plus simple de default dans docker que dans le code  Y'a os.LookupEnv qui existe :
https://golangbyexample.com/check-environment-variable-set-go/

2020-12-01 18:52 UTC, antoinedeschenes commented
tu crées une dépendance à une env var

2020-12-02 14:40 UTC, nvanheuverzwijn requested changes

2020-12-02 14:40 UTC, nvanheuverzwijn commented on main.go
> +		log.Panicln(cv)
Je crois qu'ici, tu aurait `timeout = 5` et non un `log.Panicln`.
Si cv (qui est l'erreur), n'est pas nil (la variable d'environnement ne parse pas comme il faut), on met par défaut 90.

2020-12-02 14:40 UTC, nvanheuverzwijn commented on main.go
> +	} else {
Pas besoin de ce else puisque timeout aura la valeur de `Atoi` ou, s'il y a une erreur, sera de `90` par défaut.

2020-12-02 14:40 UTC, nvanheuverzwijn commented on main.go
> +	if lu {
`lu` sera toujours un bool (`true` ou `false`). LookupEnv retourne true dans `lu` si la variable existe sinon `false`.
En ce moment, si on set `HTTP_TIMEOUT`, ça va toujours retourner true et ça va toujours panic.

See https://golang.org/pkg/os/#LookupEnv
>   val, ok := os.LookupEnv(key)
> 		if !ok {
> 			fmt.Printf("%s not set\n", key)
> 		} else {
> 			fmt.Printf("%s=%s\n", key, val)
> 		}

Ce que tu dois checker, c'est si `lu` est `false`, ça veut dire que y'a pas de variable d'environnement donc `timeout = 5`.
Si `lu` est true, il y a une variable d'environnement, donc il faut caller `Atoi` dessus et setter timeout.

2020-12-02 14:40 UTC, nvanheuverzwijn commented on main.go
> +		timeout = 90
Le timeout devrait default à `5` je crois ?

2020-12-02 14:40 UTC, nvanheuverzwijn commented on main.go
> +	timeout, cv := strconv.Atoi(ti)
Ce bloc devrait probablement être bougé dans le `if lu {}`. Si on a une variable d'environnement, parse it!

2020-12-02 14:43 UTC, nvanheuverzwijn commented
@mdastous Assures toi de tester tous les use-case:
1. Variable HTTP_TIMEOUT set à un entier (`90` mettons)
2. Variable HTTP_TIMEOUT set à une string (`abc`)
3. Variable HTTP_TIMEOUT non setté

Normalement, on ferait des tests unitaires pour vérifier tout ça au lieu de le tester à bras. Mais pour là, don't worry about it, on les fera après si t'as toujours le gout de faire plus de go :)

2020-12-03 16:56 UTC, nvanheuverzwijn approved these changes
LGTM

2020-12-03 16:56 UTC, nvanheuverzwijn commented
@antoinedeschenes Looks good to you ?

2020-12-04 07:10 UTC, antoinedeschenes commented
Faudrait que ça fail quand HTTP_TIMEOUT est set, mais invalide

2020-12-04 15:26 UTC, nvanheuverzwijn reviewed
@mdastous Pour le need à Antoine, je t'ai rajouter un petit snippet de code.

2020-12-04 15:26 UTC, nvanheuverzwijn commented on main.go
> +	var timeout int
@mdastous Je te suggère ceci :
```suggestion
	var timeout int = 5  # Valeur par défaut à 5
	ti, lu := os.LookupEnv("HTTP_TIMEOUT")
        # Si on a une variable d'environnement ...
	if ( lu ) {
	    timeout, cv := strconv.Atoi(ti)
	    # ...mais qu'on est pas capable de parser la variable
	    if ( cv != nil ) {
	        # Fail here directly
	        log.Panicln("Could not convert HTTP_TIMEOUT environment variable to int")
	    }
	}
	#else {
	#    Pas besoin de ce block, HTTP_TIMEOUT n'existe pas donc on fallback sur timeout = 5 (qui est déjà set par défaut)
	#}
	# life goes on avec timeout =5!
```

2020-12-04 16:16 UTC, antoinedeschenes commented on main.go
> +	ti, _ := os.LookupEnv("HTTP_TIMEOUT")
almost there, faudrait handler le bool de LookupEnv, vu que timeout = 0 est une valeur valide

2020-12-04 16:38 UTC, antoinedeschenes approved these changes

2020-12-04 16:39 UTC, merged